### ISSUE TITLE
Username Password support?

### ISSUE THREAD

**Issue by Rotzbua** [tikagnus/mqqt#1]
Hi,
I saw your big pull request at  bluerhinos/phpMQTT and spotted this library.
It seems that you have no username password support, will this be implemented?
Best

**Comment by btica-ro** [comment]
Hi @Rotzbua. 
Yes, this library uses user and password.
Here are the lines where user and pass should be provided.

https://github.com/tikagnus/mqqt/blob/master/src/Mqqt/Mqtt/AbstractMqtt.php#L130 

https://github.com/tikagnus/mqqt/blob/b8524a9d8df4a5fd8d53b32886fa5db2d247e386/src/Mqqt/Mqtt/AbstractMqtt.php#L130

Example could be:

```
$publish = new \Mqqt\Mqtt\Publish\Publish($socket, $client_id,$keepAlive,$clean,$will,$user,$pass);
```

Regards.

**Comment by Rotzbua** [comment]
Thanks for your fast answer. Seems I was blind and didnt saw the implementation....
I already finished my tiny project (only pushing information to mqtt) with the original library. Some improvements maybe also interesting for your project https://github.com/bluerhinos/phpMQTT/pull/54 .
Best regards.
